const sanitizeForJsString = (value) => {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
};

const makePackageJson = (project) => {
  const safeName = String(project.title || 'generated-app')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'generated-app';

  return JSON.stringify(
    {
      scripts: {
        dev: 'vite --host 0.0.0.0',
        build: 'vite build',
        preview: 'vite preview'
      },
      dependencies: {
        '@vitejs/plugin-react': 'latest',
        vite: 'latest',
        react: 'latest',
        'react-dom': 'latest'
      },
      devDependencies: {},
      name: safeName,
      version: '0.1.0',
      private: true
    },
    null,
    2
  );
};

const makeAppJsx = (project) => {
  const title = sanitizeForJsString(project.title);
  const prompt = sanitizeForJsString(project.prompt);
  const appType = sanitizeForJsString(project.appType || 'web-app');
  const modelType = sanitizeForJsString(project.modelType || 'balanced');

  return `import './index.css';

const generatedSections = [
  'Clear hero section based on the original user prompt',
  'Feature cards for the main product value',
  'Call-to-action area for conversion',
  'Responsive layout for desktop and mobile'
];

function App() {
  return (
    <main className="app-shell">
      <section className="hero-card">
        <p className="eyebrow">AI Software Builder Preview</p>
        <h1>${title}</h1>
        <p className="prompt-summary">${prompt}</p>
        <div className="meta-row">
          <span>Type: ${appType}</span>
          <span>Mode: ${modelType}</span>
        </div>
        <button className="primary-button">Explore Generated App</button>
      </section>

      <section className="feature-grid">
        {generatedSections.map((section) => (
          <article className="feature-card" key={section}>
            <h2>{section}</h2>
            <p>This block is generated by the fake AI service and can be replaced by real AI output later.</p>
          </article>
        ))}
      </section>
    </main>
  );
}

export default App;
`;
};

const makeMainJsx = () => {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
};

const makeIndexCss = () => {
  return `:root {
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: #172033;
  background: #eef3ff;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
}

button {
  font: inherit;
}

.app-shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 64px 0;
}

.hero-card {
  padding: 48px;
  border-radius: 32px;
  background: white;
  box-shadow: 0 24px 80px rgba(39, 58, 112, 0.14);
}

.eyebrow {
  margin: 0 0 12px;
  color: #5267ff;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

h1 {
  margin: 0;
  font-size: clamp(2.4rem, 7vw, 5rem);
  line-height: 0.95;
}

.prompt-summary {
  max-width: 760px;
  margin: 24px 0;
  font-size: 1.1rem;
  color: #516070;
}

.meta-row {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 28px;
}

.meta-row span {
  padding: 8px 12px;
  border-radius: 999px;
  background: #edf1ff;
  color: #3d4b63;
  font-weight: 600;
}

.primary-button {
  border: 0;
  border-radius: 999px;
  padding: 14px 22px;
  color: white;
  background: #5267ff;
  cursor: pointer;
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 18px;
  margin-top: 24px;
}

.feature-card {
  padding: 24px;
  border-radius: 24px;
  background: rgba(255, 255, 255, 0.76);
  border: 1px solid rgba(82, 103, 255, 0.14);
}

.feature-card h2 {
  margin: 0 0 10px;
  font-size: 1.05rem;
}

.feature-card p {
  margin: 0;
  color: #59687d;
}
`;
};

const generateProject = async (project) => {
  // This service is intentionally fake for the MVP.
  // Later, replace this function body with a real AI provider call while keeping the same return shape.
  const plan = [
    `Analyze the prompt and identify the target app type: ${project.appType || 'web-app'}.`,
    'Create a responsive React/Vite project structure.',
    'Generate a hero section, feature grid, and conversion call-to-action.',
    'Prepare source files that the frontend can display in a code viewer.',
    'Return a preview description and mark the project as ready.'
  ];

  const files = [
    {
      path: 'package.json',
      language: 'json',
      content: makePackageJson(project)
    },
    {
      path: 'src/App.jsx',
      language: 'jsx',
      content: makeAppJsx(project)
    },
    {
      path: 'src/main.jsx',
      language: 'jsx',
      content: makeMainJsx()
    },
    {
      path: 'src/index.css',
      language: 'css',
      content: makeIndexCss()
    }
  ];

  return {
    plan,
    files,
    previewDescription: `A polished ${project.appType || 'web-app'} preview generated from: "${project.prompt}"`
  };
};

module.exports = {
  generateProject
};
